'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources.RadEditor
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile el proyecto de Visual Studio.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Modules
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.RadEditor.Modules", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Action.
        '''</summary>
        Friend Shared ReadOnly Property action() As String
            Get
                Return ResourceManager.GetString("action", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Alignment.
        '''</summary>
        Friend Shared ReadOnly Property align() As String
            Get
                Return ResourceManager.GetString("align", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ToolTip.
        '''</summary>
        Friend Shared ReadOnly Property alt() As String
            Get
                Return ResourceManager.GetString("alt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Background.
        '''</summary>
        Friend Shared ReadOnly Property bgColor() As String
            Get
                Return ResourceManager.GetString("bgColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New Window.
        '''</summary>
        Friend Shared ReadOnly Property blank() As String
            Get
                Return ResourceManager.GetString("blank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Border Width.
        '''</summary>
        Friend Shared ReadOnly Property border() As String
            Get
                Return ResourceManager.GetString("border", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Border color.
        '''</summary>
        Friend Shared ReadOnly Property borderColor() As String
            Get
                Return ResourceManager.GetString("borderColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CellPadding.
        '''</summary>
        Friend Shared ReadOnly Property cellPadding() As String
            Get
                Return ResourceManager.GetString("cellPadding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CellSpacing.
        '''</summary>
        Friend Shared ReadOnly Property cellSpacing() As String
            Get
                Return ResourceManager.GetString("cellSpacing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Classname.
        '''</summary>
        Friend Shared ReadOnly Property className() As String
            Get
                Return ResourceManager.GetString("className", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Columns.
        '''</summary>
        Friend Shared ReadOnly Property cols() As String
            Get
                Return ResourceManager.GetString("cols", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select Doctype.
        '''</summary>
        Friend Shared ReadOnly Property Doctype() As String
            Get
                Return ResourceManager.GetString("Doctype", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RemoveElement.
        '''</summary>
        Friend Shared ReadOnly Property DomInspectorRemoveElement() As String
            Get
                Return ResourceManager.GetString("DomInspectorRemoveElement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Expand Report Pane.
        '''</summary>
        Friend Shared ReadOnly Property ExpandValidator() As String
            Get
                Return ResourceManager.GetString("ExpandValidator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Height.
        '''</summary>
        Friend Shared ReadOnly Property height() As String
            Get
                Return ResourceManager.GetString("height", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a URL.
        '''</summary>
        Friend Shared ReadOnly Property href() As String
            Get
                Return ResourceManager.GetString("href", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Id.
        '''</summary>
        Friend Shared ReadOnly Property id() As String
            Get
                Return ResourceManager.GetString("id", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Media Pane.
        '''</summary>
        Friend Shared ReadOnly Property media() As String
            Get
                Return ResourceManager.GetString("media", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name.
        '''</summary>
        Friend Shared ReadOnly Property name() As String
            Get
                Return ResourceManager.GetString("name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Invalid value. Please enter a number..
        '''</summary>
        Friend Shared ReadOnly Property NodeInspectorInvalidValue() As String
            Get
                Return ResourceManager.GetString("NodeInspectorInvalidValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The selected element is .
        '''</summary>
        Friend Shared ReadOnly Property NodeInspectorSelectedElement() As String
            Get
                Return ResourceManager.GetString("NodeInspectorSelectedElement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nowrap.
        '''</summary>
        Friend Shared ReadOnly Property noWrap() As String
            Get
                Return ResourceManager.GetString("noWrap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Parent Window.
        '''</summary>
        Friend Shared ReadOnly Property parent() As String
            Get
                Return ResourceManager.GetString("parent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tag Inspector.
        '''</summary>
        Friend Shared ReadOnly Property RadEditorDomInspector() As String
            Get
                Return ResourceManager.GetString("RadEditorDomInspector", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Real-Time HTML View.
        '''</summary>
        Friend Shared ReadOnly Property RadEditorHtmlInspector() As String
            Get
                Return ResourceManager.GetString("RadEditorHtmlInspector", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Properties Inspector.
        '''</summary>
        Friend Shared ReadOnly Property RadEditorNodeInspector() As String
            Get
                Return ResourceManager.GetString("RadEditorNodeInspector", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Statistics.
        '''</summary>
        Friend Shared ReadOnly Property RadEditorStatistics() As String
            Get
                Return ResourceManager.GetString("RadEditorStatistics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a XHTML Validator.
        '''</summary>
        Friend Shared ReadOnly Property RadEditorXhtmlValidator() As String
            Get
                Return ResourceManager.GetString("RadEditorXhtmlValidator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources..
        '''</summary>
        Friend Shared ReadOnly Property ReservedResource() As String
            Get
                Return ResourceManager.GetString("ReservedResource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Rows.
        '''</summary>
        Friend Shared ReadOnly Property rows() As String
            Get
                Return ResourceManager.GetString("rows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Search Pane.
        '''</summary>
        Friend Shared ReadOnly Property search() As String
            Get
                Return ResourceManager.GetString("search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Same Window.
        '''</summary>
        Friend Shared ReadOnly Property self() As String
            Get
                Return ResourceManager.GetString("self", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Characters:.
        '''</summary>
        Friend Shared ReadOnly Property StatisticsCharacters() As String
            Get
                Return ResourceManager.GetString("StatisticsCharacters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Words:.
        '''</summary>
        Friend Shared ReadOnly Property StatisticsWords() As String
            Get
                Return ResourceManager.GetString("StatisticsWords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Target.
        '''</summary>
        Friend Shared ReadOnly Property target() As String
            Get
                Return ResourceManager.GetString("target", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Title.
        '''</summary>
        Friend Shared ReadOnly Property title() As String
            Get
                Return ResourceManager.GetString("title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Browser Window.
        '''</summary>
        Friend Shared ReadOnly Property top() As String
            Get
                Return ResourceManager.GetString("top", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Validate XHTML.
        '''</summary>
        Friend Shared ReadOnly Property ValidateXHTML() As String
            Get
                Return ResourceManager.GetString("ValidateXHTML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vertical Alignment.
        '''</summary>
        Friend Shared ReadOnly Property vAlign() As String
            Get
                Return ResourceManager.GetString("vAlign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Value.
        '''</summary>
        Friend Shared ReadOnly Property value() As String
            Get
                Return ResourceManager.GetString("value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Width.
        '''</summary>
        Friend Shared ReadOnly Property width() As String
            Get
                Return ResourceManager.GetString("width", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
