'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources.RadEditor
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile el proyecto de Visual Studio.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Tools
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.RadEditor.Tools", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a About RadEditor.
        '''</summary>
        Friend Shared ReadOnly Property AboutDialog() As String
            Get
                Return ResourceManager.GetString("AboutDialog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Set Absolute Position.
        '''</summary>
        Friend Shared ReadOnly Property AbsolutePosition() As String
            Get
                Return ResourceManager.GetString("AbsolutePosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a AJAX Spellchecker.
        '''</summary>
        Friend Shared ReadOnly Property AjaxSpellCheck() As String
            Get
                Return ResourceManager.GetString("AjaxSpellCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Alignment selector.
        '''</summary>
        Friend Shared ReadOnly Property AlignmentSelector() As String
            Get
                Return ResourceManager.GetString("AlignmentSelector", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Apply CSS Class.
        '''</summary>
        Friend Shared ReadOnly Property ApplyClass() As String
            Get
                Return ResourceManager.GetString("ApplyClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Background Color.
        '''</summary>
        Friend Shared ReadOnly Property BackColor() As String
            Get
                Return ResourceManager.GetString("BackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Bold.
        '''</summary>
        Friend Shared ReadOnly Property Bold() As String
            Get
                Return ResourceManager.GetString("Bold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cell Border.
        '''</summary>
        Friend Shared ReadOnly Property CellBorder() As String
            Get
                Return ResourceManager.GetString("CellBorder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Clipboard.
        '''</summary>
        Friend Shared ReadOnly Property Clipboard() As String
            Get
                Return ResourceManager.GetString("Clipboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ColorPicker.
        '''</summary>
        Friend Shared ReadOnly Property ColorPicker() As String
            Get
                Return ResourceManager.GetString("ColorPicker", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Content.
        '''</summary>
        Friend Shared ReadOnly Property Content() As String
            Get
                Return ResourceManager.GetString("Content", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Convert to lower case.
        '''</summary>
        Friend Shared ReadOnly Property ConvertToLower() As String
            Get
                Return ResourceManager.GetString("ConvertToLower", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Convert to upper case.
        '''</summary>
        Friend Shared ReadOnly Property ConvertToUpper() As String
            Get
                Return ResourceManager.GetString("ConvertToUpper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Copy.
        '''</summary>
        Friend Shared ReadOnly Property Copy() As String
            Get
                Return ResourceManager.GetString("Copy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Compliance Check.
        '''</summary>
        Friend Shared ReadOnly Property CSDialog() As String
            Get
                Return ResourceManager.GetString("CSDialog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cut.
        '''</summary>
        Friend Shared ReadOnly Property Cut() As String
            Get
                Return ResourceManager.GetString("Cut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Decrease Size.
        '''</summary>
        Friend Shared ReadOnly Property DecreaseSize() As String
            Get
                Return ResourceManager.GetString("DecreaseSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete Cell.
        '''</summary>
        Friend Shared ReadOnly Property DeleteCell() As String
            Get
                Return ResourceManager.GetString("DeleteCell", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete Column.
        '''</summary>
        Friend Shared ReadOnly Property DeleteColumn() As String
            Get
                Return ResourceManager.GetString("DeleteColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete Row.
        '''</summary>
        Friend Shared ReadOnly Property DeleteRow() As String
            Get
                Return ResourceManager.GetString("DeleteRow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete Table.
        '''</summary>
        Friend Shared ReadOnly Property DeleteTable() As String
            Get
                Return ResourceManager.GetString("DeleteTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete.
        '''</summary>
        Friend Shared ReadOnly Property DeleteTableItems() As String
            Get
                Return ResourceManager.GetString("DeleteTableItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Document Manager.
        '''</summary>
        Friend Shared ReadOnly Property DocumentManager() As String
            Get
                Return ResourceManager.GetString("DocumentManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Edit Content.
        '''</summary>
        Friend Shared ReadOnly Property EditContent() As String
            Get
                Return ResourceManager.GetString("EditContent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Editing.
        '''</summary>
        Friend Shared ReadOnly Property Editing() As String
            Get
                Return ResourceManager.GetString("Editing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enter Pressed.
        '''</summary>
        Friend Shared ReadOnly Property Enter() As String
            Get
                Return ResourceManager.GetString("Enter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Find And Replace.
        '''</summary>
        Friend Shared ReadOnly Property FindAndReplace() As String
            Get
                Return ResourceManager.GetString("FindAndReplace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Flash Manager.
        '''</summary>
        Friend Shared ReadOnly Property FlashManager() As String
            Get
                Return ResourceManager.GetString("FlashManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Font.
        '''</summary>
        Friend Shared ReadOnly Property Font() As String
            Get
                Return ResourceManager.GetString("Font", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Font Name.
        '''</summary>
        Friend Shared ReadOnly Property FontName() As String
            Get
                Return ResourceManager.GetString("FontName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Size.
        '''</summary>
        Friend Shared ReadOnly Property FontSize() As String
            Get
                Return ResourceManager.GetString("FontSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Foreground Color.
        '''</summary>
        Friend Shared ReadOnly Property ForeColor() As String
            Get
                Return ResourceManager.GetString("ForeColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paragraph Style.
        '''</summary>
        Friend Shared ReadOnly Property FormatBlock() As String
            Get
                Return ResourceManager.GetString("FormatBlock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Format Code Block.
        '''</summary>
        Friend Shared ReadOnly Property FormatCodeBlock() As String
            Get
                Return ResourceManager.GetString("FormatCodeBlock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Format Painter.
        '''</summary>
        Friend Shared ReadOnly Property FormatPainter() As String
            Get
                Return ResourceManager.GetString("FormatPainter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Apply Format.
        '''</summary>
        Friend Shared ReadOnly Property FormatPainterApply() As String
            Get
                Return ResourceManager.GetString("FormatPainterApply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Clear Format.
        '''</summary>
        Friend Shared ReadOnly Property FormatPainterClear() As String
            Get
                Return ResourceManager.GetString("FormatPainterClear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Copy Format.
        '''</summary>
        Friend Shared ReadOnly Property FormatPainterCopy() As String
            Get
                Return ResourceManager.GetString("FormatPainterCopy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Format Sets.
        '''</summary>
        Friend Shared ReadOnly Property FormatSets() As String
            Get
                Return ResourceManager.GetString("FormatSets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Format Stripper.
        '''</summary>
        Friend Shared ReadOnly Property FormatStripper() As String
            Get
                Return ResourceManager.GetString("FormatStripper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Help.
        '''</summary>
        Friend Shared ReadOnly Property Help() As String
            Get
                Return ResourceManager.GetString("Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Home.
        '''</summary>
        Friend Shared ReadOnly Property Home() As String
            Get
                Return ResourceManager.GetString("Home", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Image Border.
        '''</summary>
        Friend Shared ReadOnly Property ImageBorder() As String
            Get
                Return ResourceManager.GetString("ImageBorder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Image Editor.
        '''</summary>
        Friend Shared ReadOnly Property ImageEditor() As String
            Get
                Return ResourceManager.GetString("ImageEditor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Image Manager.
        '''</summary>
        Friend Shared ReadOnly Property ImageManager() As String
            Get
                Return ResourceManager.GetString("ImageManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Image Map Editor.
        '''</summary>
        Friend Shared ReadOnly Property ImageMapDialog() As String
            Get
                Return ResourceManager.GetString("ImageMapDialog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Size and Margins.
        '''</summary>
        Friend Shared ReadOnly Property ImageSizeMargins() As String
            Get
                Return ResourceManager.GetString("ImageSizeMargins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Increase Size.
        '''</summary>
        Friend Shared ReadOnly Property IncreaseSize() As String
            Get
                Return ResourceManager.GetString("IncreaseSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Indent.
        '''</summary>
        Friend Shared ReadOnly Property Indent() As String
            Get
                Return ResourceManager.GetString("Indent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert.
        '''</summary>
        Friend Shared ReadOnly Property Insert() As String
            Get
                Return ResourceManager.GetString("Insert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Anchor.
        '''</summary>
        Friend Shared ReadOnly Property InsertAnchor() As String
            Get
                Return ResourceManager.GetString("InsertAnchor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Column to the Left.
        '''</summary>
        Friend Shared ReadOnly Property InsertColumnLeft() As String
            Get
                Return ResourceManager.GetString("InsertColumnLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Column to the Right.
        '''</summary>
        Friend Shared ReadOnly Property InsertColumnRight() As String
            Get
                Return ResourceManager.GetString("InsertColumnRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Custom Links.
        '''</summary>
        Friend Shared ReadOnly Property InsertCustomLink() As String
            Get
                Return ResourceManager.GetString("InsertCustomLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Date.
        '''</summary>
        Friend Shared ReadOnly Property InsertDate() As String
            Get
                Return ResourceManager.GetString("InsertDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Email Link.
        '''</summary>
        Friend Shared ReadOnly Property InsertEmailLink() As String
            Get
                Return ResourceManager.GetString("InsertEmailLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert External Video.
        '''</summary>
        Friend Shared ReadOnly Property InsertExternalVideo() As String
            Get
                Return ResourceManager.GetString("InsertExternalVideo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Button.
        '''</summary>
        Friend Shared ReadOnly Property InsertFormButton() As String
            Get
                Return ResourceManager.GetString("InsertFormButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Checkbox.
        '''</summary>
        Friend Shared ReadOnly Property InsertFormCheckbox() As String
            Get
                Return ResourceManager.GetString("InsertFormCheckbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Form Element.
        '''</summary>
        Friend Shared ReadOnly Property InsertFormElement() As String
            Get
                Return ResourceManager.GetString("InsertFormElement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Form.
        '''</summary>
        Friend Shared ReadOnly Property InsertFormForm() As String
            Get
                Return ResourceManager.GetString("InsertFormForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Hidden.
        '''</summary>
        Friend Shared ReadOnly Property InsertFormHidden() As String
            Get
                Return ResourceManager.GetString("InsertFormHidden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Password.
        '''</summary>
        Friend Shared ReadOnly Property InsertFormPassword() As String
            Get
                Return ResourceManager.GetString("InsertFormPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Radio.
        '''</summary>
        Friend Shared ReadOnly Property InsertFormRadio() As String
            Get
                Return ResourceManager.GetString("InsertFormRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Reset.
        '''</summary>
        Friend Shared ReadOnly Property InsertFormReset() As String
            Get
                Return ResourceManager.GetString("InsertFormReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Select.
        '''</summary>
        Friend Shared ReadOnly Property InsertFormSelect() As String
            Get
                Return ResourceManager.GetString("InsertFormSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Submit.
        '''</summary>
        Friend Shared ReadOnly Property InsertFormSubmit() As String
            Get
                Return ResourceManager.GetString("InsertFormSubmit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Textbox.
        '''</summary>
        Friend Shared ReadOnly Property InsertFormText() As String
            Get
                Return ResourceManager.GetString("InsertFormText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Textarea.
        '''</summary>
        Friend Shared ReadOnly Property InsertFormTextarea() As String
            Get
                Return ResourceManager.GetString("InsertFormTextarea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Groupbox.
        '''</summary>
        Friend Shared ReadOnly Property InsertGroupbox() As String
            Get
                Return ResourceManager.GetString("InsertGroupbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Horizontal Rule.
        '''</summary>
        Friend Shared ReadOnly Property InsertHorizontalRule() As String
            Get
                Return ResourceManager.GetString("InsertHorizontalRule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Image.
        '''</summary>
        Friend Shared ReadOnly Property InsertImage() As String
            Get
                Return ResourceManager.GetString("InsertImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Link.
        '''</summary>
        Friend Shared ReadOnly Property InsertLink() As String
            Get
                Return ResourceManager.GetString("InsertLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Numbered List.
        '''</summary>
        Friend Shared ReadOnly Property InsertOrderedList() As String
            Get
                Return ResourceManager.GetString("InsertOrderedList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New Paragraph.
        '''</summary>
        Friend Shared ReadOnly Property InsertParagraph() As String
            Get
                Return ResourceManager.GetString("InsertParagraph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Row Above.
        '''</summary>
        Friend Shared ReadOnly Property InsertRowAbove() As String
            Get
                Return ResourceManager.GetString("InsertRowAbove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Row Below.
        '''</summary>
        Friend Shared ReadOnly Property InsertRowBelow() As String
            Get
                Return ResourceManager.GetString("InsertRowBelow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Code Snippet.
        '''</summary>
        Friend Shared ReadOnly Property InsertSnippet() As String
            Get
                Return ResourceManager.GetString("InsertSnippet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Symbol.
        '''</summary>
        Friend Shared ReadOnly Property InsertSymbol() As String
            Get
                Return ResourceManager.GetString("InsertSymbol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Table.
        '''</summary>
        Friend Shared ReadOnly Property InsertTable() As String
            Get
                Return ResourceManager.GetString("InsertTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Table.
        '''</summary>
        Friend Shared ReadOnly Property InsertTableDialog() As String
            Get
                Return ResourceManager.GetString("InsertTableDialog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert.
        '''</summary>
        Friend Shared ReadOnly Property InsertTableItems() As String
            Get
                Return ResourceManager.GetString("InsertTableItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Table.
        '''</summary>
        Friend Shared ReadOnly Property InsertTableLight() As String
            Get
                Return ResourceManager.GetString("InsertTableLight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert Time.
        '''</summary>
        Friend Shared ReadOnly Property InsertTime() As String
            Get
                Return ResourceManager.GetString("InsertTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Bullet List.
        '''</summary>
        Friend Shared ReadOnly Property InsertUnorderedList() As String
            Get
                Return ResourceManager.GetString("InsertUnorderedList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Italic.
        '''</summary>
        Friend Shared ReadOnly Property Italic() As String
            Get
                Return ResourceManager.GetString("Italic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Align Center.
        '''</summary>
        Friend Shared ReadOnly Property JustifyCenter() As String
            Get
                Return ResourceManager.GetString("JustifyCenter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Justify.
        '''</summary>
        Friend Shared ReadOnly Property JustifyFull() As String
            Get
                Return ResourceManager.GetString("JustifyFull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Align Left.
        '''</summary>
        Friend Shared ReadOnly Property JustifyLeft() As String
            Get
                Return ResourceManager.GetString("JustifyLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Remove alignment.
        '''</summary>
        Friend Shared ReadOnly Property JustifyNone() As String
            Get
                Return ResourceManager.GetString("JustifyNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Align Right.
        '''</summary>
        Friend Shared ReadOnly Property JustifyRight() As String
            Get
                Return ResourceManager.GetString("JustifyRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hyperlink Manager.
        '''</summary>
        Friend Shared ReadOnly Property LinkManager() As String
            Get
                Return ResourceManager.GetString("LinkManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Links.
        '''</summary>
        Friend Shared ReadOnly Property Links() As String
            Get
                Return ResourceManager.GetString("Links", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Media.
        '''</summary>
        Friend Shared ReadOnly Property Media() As String
            Get
                Return ResourceManager.GetString("Media", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Media Manager.
        '''</summary>
        Friend Shared ReadOnly Property MediaManager() As String
            Get
                Return ResourceManager.GetString("MediaManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Merge Cells Horizontally.
        '''</summary>
        Friend Shared ReadOnly Property MergeColumns() As String
            Get
                Return ResourceManager.GetString("MergeColumns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Merge Cells Vertically.
        '''</summary>
        Friend Shared ReadOnly Property MergeRows() As String
            Get
                Return ResourceManager.GetString("MergeRows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Merge and Split Cells.
        '''</summary>
        Friend Shared ReadOnly Property MergeSplitCells() As String
            Get
                Return ResourceManager.GetString("MergeSplitCells", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Edit.
        '''</summary>
        Friend Shared ReadOnly Property MobileEdit() As String
            Get
                Return ResourceManager.GetString("MobileEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Table Properties.
        '''</summary>
        Friend Shared ReadOnly Property MobileTableProperties() As String
            Get
                Return ResourceManager.GetString("MobileTableProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Module Manager.
        '''</summary>
        Friend Shared ReadOnly Property ModuleManager() As String
            Get
                Return ResourceManager.GetString("ModuleManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Outdent.
        '''</summary>
        Friend Shared ReadOnly Property Outdent() As String
            Get
                Return ResourceManager.GetString("Outdent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Page Properties.
        '''</summary>
        Friend Shared ReadOnly Property PageProperties() As String
            Get
                Return ResourceManager.GetString("PageProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paragraph.
        '''</summary>
        Friend Shared ReadOnly Property Paragraph() As String
            Get
                Return ResourceManager.GetString("Paragraph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paste.
        '''</summary>
        Friend Shared ReadOnly Property Paste() As String
            Get
                Return ResourceManager.GetString("Paste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paste As Html.
        '''</summary>
        Friend Shared ReadOnly Property PasteAsHtml() As String
            Get
                Return ResourceManager.GetString("PasteAsHtml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paste from Word.
        '''</summary>
        Friend Shared ReadOnly Property PasteFromWord() As String
            Get
                Return ResourceManager.GetString("PasteFromWord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paste from Word, strip font.
        '''</summary>
        Friend Shared ReadOnly Property PasteFromWordNoFontsNoSizes() As String
            Get
                Return ResourceManager.GetString("PasteFromWordNoFontsNoSizes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paste Html.
        '''</summary>
        Friend Shared ReadOnly Property PasteHtml() As String
            Get
                Return ResourceManager.GetString("PasteHtml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paste Markdown.
        '''</summary>
        Friend Shared ReadOnly Property PasteMarkdown() As String
            Get
                Return ResourceManager.GetString("PasteMarkdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paste Plain Text.
        '''</summary>
        Friend Shared ReadOnly Property PastePlainText() As String
            Get
                Return ResourceManager.GetString("PastePlainText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paste Options.
        '''</summary>
        Friend Shared ReadOnly Property PasteStrip() As String
            Get
                Return ResourceManager.GetString("PasteStrip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Preferences.
        '''</summary>
        Friend Shared ReadOnly Property Preferences() As String
            Get
                Return ResourceManager.GetString("Preferences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Print.
        '''</summary>
        Friend Shared ReadOnly Property Print() As String
            Get
                Return ResourceManager.GetString("Print", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Proofing.
        '''</summary>
        Friend Shared ReadOnly Property Proofing() As String
            Get
                Return ResourceManager.GetString("Proofing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Real font size.
        '''</summary>
        Friend Shared ReadOnly Property RealFontSize() As String
            Get
                Return ResourceManager.GetString("RealFontSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Redo.
        '''</summary>
        Friend Shared ReadOnly Property Redo() As String
            Get
                Return ResourceManager.GetString("Redo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Repeat Last Command.
        '''</summary>
        Friend Shared ReadOnly Property RepeatLastCommand() As String
            Get
                Return ResourceManager.GetString("RepeatLastCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources..
        '''</summary>
        Friend Shared ReadOnly Property ReservedResource() As String
            Get
                Return ResourceManager.GetString("ReservedResource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Review.
        '''</summary>
        Friend Shared ReadOnly Property Review() As String
            Get
                Return ResourceManager.GetString("Review", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select All.
        '''</summary>
        Friend Shared ReadOnly Property SelectAll() As String
            Get
                Return ResourceManager.GetString("SelectAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cell Properties.
        '''</summary>
        Friend Shared ReadOnly Property SetCellProperties() As String
            Get
                Return ResourceManager.GetString("SetCellProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Properties....
        '''</summary>
        Friend Shared ReadOnly Property SetImageProperties() As String
            Get
                Return ResourceManager.GetString("SetImageProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Properties....
        '''</summary>
        Friend Shared ReadOnly Property SetLinkProperties() As String
            Get
                Return ResourceManager.GetString("SetLinkProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Table Properties.
        '''</summary>
        Friend Shared ReadOnly Property SetTableProperties() As String
            Get
                Return ResourceManager.GetString("SetTableProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Silverlight Manager.
        '''</summary>
        Friend Shared ReadOnly Property SilverlightManager() As String
            Get
                Return ResourceManager.GetString("SilverlightManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Size and Margins.
        '''</summary>
        Friend Shared ReadOnly Property SizeMargins() As String
            Get
                Return ResourceManager.GetString("SizeMargins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Spellchecker.
        '''</summary>
        Friend Shared ReadOnly Property SpellCheck() As String
            Get
                Return ResourceManager.GetString("SpellCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Split Cell Vertically.
        '''</summary>
        Friend Shared ReadOnly Property SplitCell() As String
            Get
                Return ResourceManager.GetString("SplitCell", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Split Cell Horizontally.
        '''</summary>
        Friend Shared ReadOnly Property SplitCellHorizontal() As String
            Get
                Return ResourceManager.GetString("SplitCellHorizontal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Strikethrough.
        '''</summary>
        Friend Shared ReadOnly Property StrikeThrough() As String
            Get
                Return ResourceManager.GetString("StrikeThrough", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Strip All Formatting.
        '''</summary>
        Friend Shared ReadOnly Property StripAll() As String
            Get
                Return ResourceManager.GetString("StripAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Strip Css Formatting.
        '''</summary>
        Friend Shared ReadOnly Property StripCss() As String
            Get
                Return ResourceManager.GetString("StripCss", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Strip Font Elements.
        '''</summary>
        Friend Shared ReadOnly Property StripFont() As String
            Get
                Return ResourceManager.GetString("StripFont", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Strip Span Elements.
        '''</summary>
        Friend Shared ReadOnly Property StripSpan() As String
            Get
                Return ResourceManager.GetString("StripSpan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Strip Word Formatting.
        '''</summary>
        Friend Shared ReadOnly Property StripWord() As String
            Get
                Return ResourceManager.GetString("StripWord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Style Builder.
        '''</summary>
        Friend Shared ReadOnly Property StyleBuilder() As String
            Get
                Return ResourceManager.GetString("StyleBuilder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Styles.
        '''</summary>
        Friend Shared ReadOnly Property Styles() As String
            Get
                Return ResourceManager.GetString("Styles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Subscript.
        '''</summary>
        Friend Shared ReadOnly Property Subscript() As String
            Get
                Return ResourceManager.GetString("Subscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SuperScript.
        '''</summary>
        Friend Shared ReadOnly Property Superscript() As String
            Get
                Return ResourceManager.GetString("Superscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Table Border.
        '''</summary>
        Friend Shared ReadOnly Property TableBorder() As String
            Get
                Return ResourceManager.GetString("TableBorder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tables.
        '''</summary>
        Friend Shared ReadOnly Property Tables() As String
            Get
                Return ResourceManager.GetString("Tables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Table Wizard.
        '''</summary>
        Friend Shared ReadOnly Property TableWizard() As String
            Get
                Return ResourceManager.GetString("TableWizard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Template Manager.
        '''</summary>
        Friend Shared ReadOnly Property TemplateManager() As String
            Get
                Return ResourceManager.GetString("TemplateManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dock all Floating Toolbars/Modules.
        '''</summary>
        Friend Shared ReadOnly Property ToggleDocking() As String
            Get
                Return ResourceManager.GetString("ToggleDocking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Toggle Edit Mode.
        '''</summary>
        Friend Shared ReadOnly Property ToggleEditMode() As String
            Get
                Return ResourceManager.GetString("ToggleEditMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Toggle Floating Toolbar.
        '''</summary>
        Friend Shared ReadOnly Property ToggleFloatingToolbar() As String
            Get
                Return ResourceManager.GetString("ToggleFloatingToolbar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Toggle Full Screen Mode.
        '''</summary>
        Friend Shared ReadOnly Property ToggleScreenMode() As String
            Get
                Return ResourceManager.GetString("ToggleScreenMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Show/Hide Border.
        '''</summary>
        Friend Shared ReadOnly Property ToggleTableBorder() As String
            Get
                Return ResourceManager.GetString("ToggleTableBorder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Underline.
        '''</summary>
        Friend Shared ReadOnly Property Underline() As String
            Get
                Return ResourceManager.GetString("Underline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Undo.
        '''</summary>
        Friend Shared ReadOnly Property Undo() As String
            Get
                Return ResourceManager.GetString("Undo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Remove Link.
        '''</summary>
        Friend Shared ReadOnly Property Unlink() As String
            Get
                Return ResourceManager.GetString("Unlink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a View.
        '''</summary>
        Friend Shared ReadOnly Property View() As String
            Get
                Return ResourceManager.GetString("View", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a XHTML Validator.
        '''</summary>
        Friend Shared ReadOnly Property XhtmlValidator() As String
            Get
                Return ResourceManager.GetString("XhtmlValidator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Zoom.
        '''</summary>
        Friend Shared ReadOnly Property Zoom() As String
            Get
                Return ResourceManager.GetString("Zoom", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
