'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources.RadEditor
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile el proyecto de Visual Studio.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Main
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.RadEditor.Main", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Add Custom Color....
        '''</summary>
        Friend Shared ReadOnly Property AddCustomColor() As String
            Get
                Return ResourceManager.GetString("AddCustomColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Add Hex Color....
        '''</summary>
        Friend Shared ReadOnly Property AddCustomHexColor() As String
            Get
                Return ResourceManager.GetString("AddCustomHexColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a successfully added to dictionary.
        '''</summary>
        Friend Shared ReadOnly Property AddCustomWordSuccess() As String
            Get
                Return ResourceManager.GetString("AddCustomWordSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Add to dictionary.
        '''</summary>
        Friend Shared ReadOnly Property AddToDictionary() As String
            Get
                Return ResourceManager.GetString("AddToDictionary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The content you are trying to paste has MS Word formatting.
        '''Would you like to clean it?.
        '''</summary>
        Friend Shared ReadOnly Property AskWordCleaning() As String
            Get
                Return ResourceManager.GetString("AskWordCleaning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property CancelButton() As String
            Get
                Return ResourceManager.GetString("CancelButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property CancelTable() As String
            Get
                Return ResourceManager.GetString("CancelTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cell Properties.
        '''</summary>
        Friend Shared ReadOnly Property CellProperties() As String
            Get
                Return ResourceManager.GetString("CellProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please, select a cell to set its properties!.
        '''</summary>
        Friend Shared ReadOnly Property CellWarning() As String
            Get
                Return ResourceManager.GetString("CellWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Manually.
        '''</summary>
        Friend Shared ReadOnly Property ChangeWordString() As String
            Get
                Return ResourceManager.GetString("ChangeWordString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Clear.
        '''</summary>
        Friend Shared ReadOnly Property Clear() As String
            Get
                Return ResourceManager.GetString("Clear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a All HTML Tags.
        '''</summary>
        Friend Shared ReadOnly Property ClearAllHtmlTags() As String
            Get
                Return ResourceManager.GetString("ClearAllHtmlTags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Clear Class.
        '''</summary>
        Friend Shared ReadOnly Property ClearClass() As String
            Get
                Return ResourceManager.GetString("ClearClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cascading Style Sheets.
        '''</summary>
        Friend Shared ReadOnly Property ClearCssFormatting() As String
            Get
                Return ResourceManager.GetString("ClearCssFormatting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Font Tags.
        '''</summary>
        Friend Shared ReadOnly Property ClearFontTags() As String
            Get
                Return ResourceManager.GetString("ClearFontTags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Clear Formatting.
        '''</summary>
        Friend Shared ReadOnly Property ClearFormatting() As String
            Get
                Return ResourceManager.GetString("ClearFormatting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Span Tags.
        '''</summary>
        Friend Shared ReadOnly Property ClearSpanTags() As String
            Get
                Return ResourceManager.GetString("ClearSpanTags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Clear Style.
        '''</summary>
        Friend Shared ReadOnly Property ClearStyle() As String
            Get
                Return ResourceManager.GetString("ClearStyle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Microsoft Word Formatting.
        '''</summary>
        Friend Shared ReadOnly Property ClearWordFormatting() As String
            Get
                Return ResourceManager.GetString("ClearWordFormatting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Spelling Changes.
        '''</summary>
        Friend Shared ReadOnly Property CorrectSpelling() As String
            Get
                Return ResourceManager.GetString("CorrectSpelling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Create Link.
        '''</summary>
        Friend Shared ReadOnly Property CreateLink() As String
            Get
                Return ResourceManager.GetString("CreateLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dialogs.
        '''</summary>
        Friend Shared ReadOnly Property DialogToolbar() As String
            Get
                Return ResourceManager.GetString("DialogToolbar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dropdowns.
        '''</summary>
        Friend Shared ReadOnly Property DropdownToolbar() As String
            Get
                Return ResourceManager.GetString("DropdownToolbar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enhanced Edit.
        '''</summary>
        Friend Shared ReadOnly Property EnhancedEditToolbar() As String
            Get
                Return ResourceManager.GetString("EnhancedEditToolbar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The added HTML code exceeded the character limit.
        '''</summary>
        Friend Shared ReadOnly Property ExceededHtmlLength() As String
            Get
                Return ResourceManager.GetString("ExceededHtmlLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The added text exceeded the character limit.
        '''</summary>
        Friend Shared ReadOnly Property ExceededTextLength() As String
            Get
                Return ResourceManager.GetString("ExceededTextLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Open file...
        '''</summary>
        Friend Shared ReadOnly Property FileOpen() As String
            Get
                Return ResourceManager.GetString("FileOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Save as....
        '''</summary>
        Friend Shared ReadOnly Property FileSaveAs() As String
            Get
                Return ResourceManager.GetString("FileSaveAs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Button.
        '''</summary>
        Friend Shared ReadOnly Property FormButton() As String
            Get
                Return ResourceManager.GetString("FormButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Checkbox.
        '''</summary>
        Friend Shared ReadOnly Property FormCheckbox() As String
            Get
                Return ResourceManager.GetString("FormCheckbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error! Form elements are only supported when the content area is set to Iframe!.
        '''</summary>
        Friend Shared ReadOnly Property FormElementsAreSupportedByIframeError() As String
            Get
                Return ResourceManager.GetString("FormElementsAreSupportedByIframeError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Form.
        '''</summary>
        Friend Shared ReadOnly Property FormForm() As String
            Get
                Return ResourceManager.GetString("FormForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hidden.
        '''</summary>
        Friend Shared ReadOnly Property FormHidden() As String
            Get
                Return ResourceManager.GetString("FormHidden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password.
        '''</summary>
        Friend Shared ReadOnly Property FormPassword() As String
            Get
                Return ResourceManager.GetString("FormPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Radio button.
        '''</summary>
        Friend Shared ReadOnly Property FormRadio() As String
            Get
                Return ResourceManager.GetString("FormRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reset.
        '''</summary>
        Friend Shared ReadOnly Property FormReset() As String
            Get
                Return ResourceManager.GetString("FormReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select.
        '''</summary>
        Friend Shared ReadOnly Property FormSelect() As String
            Get
                Return ResourceManager.GetString("FormSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Submit.
        '''</summary>
        Friend Shared ReadOnly Property FormSubmit() As String
            Get
                Return ResourceManager.GetString("FormSubmit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Textbox.
        '''</summary>
        Friend Shared ReadOnly Property FormText() As String
            Get
                Return ResourceManager.GetString("FormText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Textarea.
        '''</summary>
        Friend Shared ReadOnly Property FormTextarea() As String
            Get
                Return ResourceManager.GetString("FormTextarea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RadEditor._getAllSheets called with no document object provided!.
        '''</summary>
        Friend Shared ReadOnly Property GetAllSheetsCalledWithNoDocumentError() As String
            Get
                Return ResourceManager.GetString("GetAllSheetsCalledWithNoDocumentError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a HTML Mode.
        '''</summary>
        Friend Shared ReadOnly Property HtmlMode() As String
            Get
                Return ResourceManager.GetString("HtmlMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ignore All.
        '''</summary>
        Friend Shared ReadOnly Property IgnoreAllString() As String
            Get
                Return ResourceManager.GetString("IgnoreAllString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ignore.
        '''</summary>
        Friend Shared ReadOnly Property IgnoreString() As String
            Get
                Return ResourceManager.GetString("IgnoreString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please, select an image to set its image map properties!.
        '''</summary>
        Friend Shared ReadOnly Property ImageMapWarning() As String
            Get
                Return ResourceManager.GetString("ImageMapWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Indent HTML.
        '''</summary>
        Friend Shared ReadOnly Property IndentHtml() As String
            Get
                Return ResourceManager.GetString("IndentHtml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Insert.
        '''</summary>
        Friend Shared ReadOnly Property InsertToolbar() As String
            Get
                Return ResourceManager.GetString("InsertToolbar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Main Toolbar.
        '''</summary>
        Friend Shared ReadOnly Property MainToolbar() As String
            Get
                Return ResourceManager.GetString("MainToolbar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Add Custom Color.
        '''</summary>
        Friend Shared ReadOnly Property MobileAddCustomColor() As String
            Get
                Return ResourceManager.GetString("MobileAddCustomColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Current Color.
        '''</summary>
        Friend Shared ReadOnly Property MobileCurrentColor() As String
            Get
                Return ResourceManager.GetString("MobileCurrentColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a This word occurs more than once in the text. Would you like to replace all instances?.
        '''</summary>
        Friend Shared ReadOnly Property MoreThanOnceMessage() As String
            Get
                Return ResourceManager.GetString("MoreThanOnceMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Move.
        '''</summary>
        Friend Shared ReadOnly Property MoveCommand() As String
            Get
                Return ResourceManager.GetString("MoveCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No mistakes found..
        '''</summary>
        Friend Shared ReadOnly Property NoSpellingMistakes() As String
            Get
                Return ResourceManager.GetString("NoSpellingMistakes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (no suggestions).
        '''</summary>
        Friend Shared ReadOnly Property NoSuggestions() As String
            Get
                Return ResourceManager.GetString("NoSuggestions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please, provide the custom color HEX value:.
        '''</summary>
        Friend Shared ReadOnly Property PromptColor() As String
            Get
                Return ResourceManager.GetString("PromptColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Design.
        '''</summary>
        Friend Shared ReadOnly Property RadEditorDesignMode() As String
            Get
                Return ResourceManager.GetString("RadEditorDesignMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Content....
        '''</summary>
        Friend Shared ReadOnly Property RadEditorGroupboxContent() As String
            Get
                Return ResourceManager.GetString("RadEditorGroupboxContent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Title.
        '''</summary>
        Friend Shared ReadOnly Property RadEditorGroupboxTitle() As String
            Get
                Return ResourceManager.GetString("RadEditorGroupboxTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a HTML.
        '''</summary>
        Friend Shared ReadOnly Property RadEditorHtmlMode() As String
            Get
                Return ResourceManager.GetString("RadEditorHtmlMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Preview.
        '''</summary>
        Friend Shared ReadOnly Property RadEditorPreviewMode() As String
            Get
                Return ResourceManager.GetString("RadEditorPreviewMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please, reduce the content of the field.
        '''</summary>
        Friend Shared ReadOnly Property ReduceTheConentLength() As String
            Get
                Return ResourceManager.GetString("ReduceTheConentLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources..
        '''</summary>
        Friend Shared ReadOnly Property ReservedResource() As String
            Get
                Return ResourceManager.GetString("ReservedResource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Resize Object.
        '''</summary>
        Friend Shared ReadOnly Property ResizeCommand() As String
            Get
                Return ResourceManager.GetString("ResizeCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Set HTML.
        '''</summary>
        Friend Shared ReadOnly Property SetHtml() As String
            Get
                Return ResourceManager.GetString("SetHtml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error! Set EditorContentAreaMode to Iframe if you want to edit full page HTML!.
        '''</summary>
        Friend Shared ReadOnly Property SetToIframeForFullHTMLError() As String
            Get
                Return ResourceManager.GetString("SetToIframeForFullHTMLError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Show toolbar.
        '''</summary>
        Friend Shared ReadOnly Property ShowToolbarTooltip() As String
            Get
                Return ResourceManager.GetString("ShowToolbarTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The Spell Check is complete!.
        '''</summary>
        Friend Shared ReadOnly Property SpellCheckComplete() As String
            Get
                Return ResourceManager.GetString("SpellCheckComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Finish spellchecking.
        '''</summary>
        Friend Shared ReadOnly Property SpellCheckEnd() As String
            Get
                Return ResourceManager.GetString("SpellCheckEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Spelling Change.
        '''</summary>
        Friend Shared ReadOnly Property SpellingChange() As String
            Get
                Return ResourceManager.GetString("SpellingChange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Spell checking in progress....
        '''</summary>
        Friend Shared ReadOnly Property SpellingInProgress() As String
            Get
                Return ResourceManager.GetString("SpellingInProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Spell checking mode. Misspelled words are highlighted in yellow..
        '''</summary>
        Friend Shared ReadOnly Property SpellingMode() As String
            Get
                Return ResourceManager.GetString("SpellingMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Table.
        '''</summary>
        Friend Shared ReadOnly Property Table() As String
            Get
                Return ResourceManager.GetString("Table", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Table.
        '''</summary>
        Friend Shared ReadOnly Property TableToolbar() As String
            Get
                Return ResourceManager.GetString("TableToolbar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please, select a table to set its properties!.
        '''</summary>
        Friend Shared ReadOnly Property TableWarning() As String
            Get
                Return ResourceManager.GetString("TableWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RadEditor Toolbar.
        '''</summary>
        Friend Shared ReadOnly Property ToolbarCaption() As String
            Get
                Return ResourceManager.GetString("ToolbarCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a This tool is not supported by Mozilla/Netscape browsers..
        '''</summary>
        Friend Shared ReadOnly Property ToolNotSupportedByNetscape() As String
            Get
                Return ResourceManager.GetString("ToolNotSupportedByNetscape", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Typing....
        '''</summary>
        Friend Shared ReadOnly Property Typing() As String
            Get
                Return ResourceManager.GetString("Typing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a You cannot undo further while in spellcheck mode. Please finish spellchecking first..
        '''</summary>
        Friend Shared ReadOnly Property UndoDisabledMessage() As String
            Get
                Return ResourceManager.GetString("UndoDisabledMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Update.
        '''</summary>
        Friend Shared ReadOnly Property UpdateButton() As String
            Get
                Return ResourceManager.GetString("UpdateButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please use Ctrl+C to Copy (Cmd+C on Mac).
        '''</summary>
        Friend Shared ReadOnly Property UseCtrlC() As String
            Get
                Return ResourceManager.GetString("UseCtrlC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please use Ctrl+V to Paste (Cmd+V on Mac).
        '''</summary>
        Friend Shared ReadOnly Property UseCtrlV() As String
            Get
                Return ResourceManager.GetString("UseCtrlV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please use Ctrl+X to Cut (Cmd+X on Mac).
        '''</summary>
        Friend Shared ReadOnly Property UseCtrlX() As String
            Get
                Return ResourceManager.GetString("UseCtrlX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CSS Class.
        '''</summary>
        Friend Shared ReadOnly Property _Class() As String
            Get
                Return ResourceManager.GetString("Class", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
