'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources.RadImageGallery
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile el proyecto de Visual Studio.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Main
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.RadImageGallery.Main", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cerrar.
        '''</summary>
        Friend Shared ReadOnly Property CloseButtonText() As String
            Get
                Return ResourceManager.GetString("CloseButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Clic para Pantalla Completa.
        '''</summary>
        Friend Shared ReadOnly Property EnterFullScreenButtonText() As String
            Get
                Return ResourceManager.GetString("EnterFullScreenButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Salir de Pantalla Completa.
        '''</summary>
        Friend Shared ReadOnly Property ExitFullScreenButtonText() As String
            Get
                Return ResourceManager.GetString("ExitFullScreenButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ocultar Miniatura.
        '''</summary>
        Friend Shared ReadOnly Property HideThumbnailsButtonText() As String
            Get
                Return ResourceManager.GetString("HideThumbnailsButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Foto {0} de {1}.
        '''</summary>
        Friend Shared ReadOnly Property ItemsCounterFormat() As String
            Get
                Return ResourceManager.GetString("ItemsCounterFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a {0} / {1}.
        '''</summary>
        Friend Shared ReadOnly Property MobileItemsCounterFormat() As String
            Get
                Return ResourceManager.GetString("MobileItemsCounterFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Siguiente Foto.
        '''</summary>
        Friend Shared ReadOnly Property NextImageButtonText() As String
            Get
                Return ResourceManager.GetString("NextImageButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Foto {0} de {1}.
        '''</summary>
        Friend Shared ReadOnly Property PagerTextFormat() As String
            Get
                Return ResourceManager.GetString("PagerTextFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Parar Presentacion.
        '''</summary>
        Friend Shared ReadOnly Property PauseButtonText() As String
            Get
                Return ResourceManager.GetString("PauseButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Empezar Presentacion.
        '''</summary>
        Friend Shared ReadOnly Property PlayButtonText() As String
            Get
                Return ResourceManager.GetString("PlayButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Anterior Foto.
        '''</summary>
        Friend Shared ReadOnly Property PrevImageButtonText() As String
            Get
                Return ResourceManager.GetString("PrevImageButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please do not remove this key..
        '''</summary>
        Friend Shared ReadOnly Property ReservedResource() As String
            Get
                Return ResourceManager.GetString("ReservedResource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Siguiente.
        '''</summary>
        Friend Shared ReadOnly Property ScrollNextButtonText() As String
            Get
                Return ResourceManager.GetString("ScrollNextButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Anterior.
        '''</summary>
        Friend Shared ReadOnly Property ScrollPrevButtonText() As String
            Get
                Return ResourceManager.GetString("ScrollPrevButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mostrar Miniaturas.
        '''</summary>
        Friend Shared ReadOnly Property ShowThumbnailsButtonText() As String
            Get
                Return ResourceManager.GetString("ShowThumbnailsButtonText", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
