'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources.RadSpell
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile el proyecto de Visual Studio.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Dialog
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.RadSpell.Dialog", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Add Custom.
        '''</summary>
        Friend Shared ReadOnly Property AddCustom() As String
            Get
                Return ResourceManager.GetString("AddCustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to add &apos;.
        '''</summary>
        Friend Shared ReadOnly Property AddWord1() As String
            Get
                Return ResourceManager.GetString("AddWord1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &apos; to the custom dictionary?.
        '''</summary>
        Friend Shared ReadOnly Property AddWord2() As String
            Get
                Return ResourceManager.GetString("AddWord2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Close.
        '''</summary>
        Friend Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change.
        '''</summary>
        Friend Shared ReadOnly Property Change() As String
            Get
                Return ResourceManager.GetString("Change", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change All.
        '''</summary>
        Friend Shared ReadOnly Property ChangeAll() As String
            Get
                Return ResourceManager.GetString("ChangeAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a You have made changes to the text..
        '''</summary>
        Friend Shared ReadOnly Property ChangesMade() As String
            Get
                Return ResourceManager.GetString("ChangesMade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Do you want to apply or cancel the changes to the text so far?.
        '''</summary>
        Friend Shared ReadOnly Property Confirm() As String
            Get
                Return ResourceManager.GetString("Confirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Help.
        '''</summary>
        Friend Shared ReadOnly Property Help() As String
            Get
                Return ResourceManager.GetString("Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ignore.
        '''</summary>
        Friend Shared ReadOnly Property Ignore() As String
            Get
                Return ResourceManager.GetString("Ignore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ignore All.
        '''</summary>
        Friend Shared ReadOnly Property IgnoreAll() As String
            Get
                Return ResourceManager.GetString("IgnoreAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a You don&apos;t have permission to access this page or your cookie has expired!&lt;br /&gt;Please, refresh the page!.
        '''</summary>
        Friend Shared ReadOnly Property NoPermission() As String
            Get
                Return ResourceManager.GetString("NoPermission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No suggestions.
        '''</summary>
        Friend Shared ReadOnly Property Nosuggestions() As String
            Get
                Return ResourceManager.GetString("Nosuggestions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Not in Dictionary:.
        '''</summary>
        Friend Shared ReadOnly Property NotInDictionary() As String
            Get
                Return ResourceManager.GetString("NotInDictionary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Spell Checking in progress.....
        '''</summary>
        Friend Shared ReadOnly Property ProgressMessage() As String
            Get
                Return ResourceManager.GetString("ProgressMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please do not change/remove this resource. .
        '''</summary>
        Friend Shared ReadOnly Property ReservedResource() As String
            Get
                Return ResourceManager.GetString("ReservedResource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The Spell Check is complete!.
        '''</summary>
        Friend Shared ReadOnly Property SpellCheckComplete() As String
            Get
                Return ResourceManager.GetString("SpellCheckComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Suggestions:.
        '''</summary>
        Friend Shared ReadOnly Property Suggestions() As String
            Get
                Return ResourceManager.GetString("Suggestions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Spell Check.
        '''</summary>
        Friend Shared ReadOnly Property Title() As String
            Get
                Return ResourceManager.GetString("Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Undo.
        '''</summary>
        Friend Shared ReadOnly Property Undo() As String
            Get
                Return ResourceManager.GetString("Undo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Undo Edit.
        '''</summary>
        Friend Shared ReadOnly Property UndoEdit() As String
            Get
                Return ResourceManager.GetString("UndoEdit", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
