'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources.RadScheduler
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile el proyecto de Visual Studio.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Main
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.RadScheduler.Main", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a After.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedAfter() As String
            Get
                Return ResourceManager.GetString("AdvancedAfter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a All day.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedAllDayEvent() As String
            Get
                Return ResourceManager.GetString("AdvancedAllDayEvent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedCalendarCancel() As String
            Get
                Return ResourceManager.GetString("AdvancedCalendarCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a OK.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedCalendarOK() As String
            Get
                Return ResourceManager.GetString("AdvancedCalendarOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Today.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedCalendarToday() As String
            Get
                Return ResourceManager.GetString("AdvancedCalendarToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Close.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedClose() As String
            Get
                Return ResourceManager.GetString("AdvancedClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Daily.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedDaily() As String
            Get
                Return ResourceManager.GetString("AdvancedDaily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Day.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedDay() As String
            Get
                Return ResourceManager.GetString("AdvancedDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Day of the month.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedDayOfMonth() As String
            Get
                Return ResourceManager.GetString("AdvancedDayOfMonth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Day of the week.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedDayOfWeek() As String
            Get
                Return ResourceManager.GetString("AdvancedDayOfWeek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a day(s).
        '''</summary>
        Friend Shared ReadOnly Property AdvancedDays() As String
            Get
                Return ResourceManager.GetString("AdvancedDays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedDescription() As String
            Get
                Return ResourceManager.GetString("AdvancedDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Done.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedDone() As String
            Get
                Return ResourceManager.GetString("AdvancedDone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Edit Appointment.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEditAppointment() As String
            Get
                Return ResourceManager.GetString("AdvancedEditAppointment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a End after.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEndAfter() As String
            Get
                Return ResourceManager.GetString("AdvancedEndAfter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a End by.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEndByThisDate() As String
            Get
                Return ResourceManager.GetString("AdvancedEndByThisDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a End date is required.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEndDateRequired() As String
            Get
                Return ResourceManager.GetString("AdvancedEndDateRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a End time is required.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEndTimeRequired() As String
            Get
                Return ResourceManager.GetString("AdvancedEndTimeRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Every.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEvery() As String
            Get
                Return ResourceManager.GetString("AdvancedEvery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Every weekday.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEveryWeekday() As String
            Get
                Return ResourceManager.GetString("AdvancedEveryWeekday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Every working day.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEveryWorkingDay() As String
            Get
                Return ResourceManager.GetString("AdvancedEveryWorkingDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a first.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedFirst() As String
            Get
                Return ResourceManager.GetString("AdvancedFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a fourth.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedFourth() As String
            Get
                Return ResourceManager.GetString("AdvancedFourth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Start time.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedFrom() As String
            Get
                Return ResourceManager.GetString("AdvancedFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hourly.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedHourly() As String
            Get
                Return ResourceManager.GetString("AdvancedHourly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a hour(s).
        '''</summary>
        Friend Shared ReadOnly Property AdvancedHours() As String
            Get
                Return ResourceManager.GetString("AdvancedHours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Invalid number.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedInvalidNumber() As String
            Get
                Return ResourceManager.GetString("AdvancedInvalidNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a last.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedLast() As String
            Get
                Return ResourceManager.GetString("AdvancedLast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a day.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedMaskDay() As String
            Get
                Return ResourceManager.GetString("AdvancedMaskDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a weekday.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedMaskWeekday() As String
            Get
                Return ResourceManager.GetString("AdvancedMaskWeekday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a weekend day.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedMaskWeekendDay() As String
            Get
                Return ResourceManager.GetString("AdvancedMaskWeekendDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Monthly.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedMonthly() As String
            Get
                Return ResourceManager.GetString("AdvancedMonthly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a month(s).
        '''</summary>
        Friend Shared ReadOnly Property AdvancedMonths() As String
            Get
                Return ResourceManager.GetString("AdvancedMonths", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a More details.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedMoreDetails() As String
            Get
                Return ResourceManager.GetString("AdvancedMoreDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Never.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedNever() As String
            Get
                Return ResourceManager.GetString("AdvancedNever", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New Appointment.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedNewAppointment() As String
            Get
                Return ResourceManager.GetString("AdvancedNewAppointment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No end date.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedNoEndDate() As String
            Get
                Return ResourceManager.GetString("AdvancedNoEndDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a occurrences.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedOccurrences() As String
            Get
                Return ResourceManager.GetString("AdvancedOccurrences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a of.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedOf() As String
            Get
                Return ResourceManager.GetString("AdvancedOf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a of every.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedOfEvery() As String
            Get
                Return ResourceManager.GetString("AdvancedOfEvery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a On.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedOn() As String
            Get
                Return ResourceManager.GetString("AdvancedOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Range of recurrence:.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRange() As String
            Get
                Return ResourceManager.GetString("AdvancedRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recur every.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRecurEvery() As String
            Get
                Return ResourceManager.GetString("AdvancedRecurEvery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recurrence.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRecurrence() As String
            Get
                Return ResourceManager.GetString("AdvancedRecurrence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recurring task.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRecurringAppointment() As String
            Get
                Return ResourceManager.GetString("AdvancedRecurringAppointment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Repeat.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRepeat() As String
            Get
                Return ResourceManager.GetString("AdvancedRepeat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Repeat Appointment.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRepeatAppointment() As String
            Get
                Return ResourceManager.GetString("AdvancedRepeatAppointment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Repeat End.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRepeatEnd() As String
            Get
                Return ResourceManager.GetString("AdvancedRepeatEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Repeat On.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRepeatOn() As String
            Get
                Return ResourceManager.GetString("AdvancedRepeatOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a reset exceptions.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedReset() As String
            Get
                Return ResourceManager.GetString("AdvancedReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a second.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedSecond() As String
            Get
                Return ResourceManager.GetString("AdvancedSecond", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Start date is required.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedStartDateRequired() As String
            Get
                Return ResourceManager.GetString("AdvancedStartDateRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Start time must be before end time.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedStartTimeBeforeEndTime() As String
            Get
                Return ResourceManager.GetString("AdvancedStartTimeBeforeEndTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Start time is required.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedStartTimeRequired() As String
            Get
                Return ResourceManager.GetString("AdvancedStartTimeRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Subject.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedSubject() As String
            Get
                Return ResourceManager.GetString("AdvancedSubject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please provide appointment subject.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedSubjectRequired() As String
            Get
                Return ResourceManager.GetString("AdvancedSubjectRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedThe() As String
            Get
                Return ResourceManager.GetString("AdvancedThe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a third.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedThird() As String
            Get
                Return ResourceManager.GetString("AdvancedThird", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Time zone.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedTimeZone() As String
            Get
                Return ResourceManager.GetString("AdvancedTimeZone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a End time.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedTo() As String
            Get
                Return ResourceManager.GetString("AdvancedTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Weekly.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedWeekly() As String
            Get
                Return ResourceManager.GetString("AdvancedWeekly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a week(s) on.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedWeeks() As String
            Get
                Return ResourceManager.GetString("AdvancedWeeks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Working....
        '''</summary>
        Friend Shared ReadOnly Property AdvancedWorking() As String
            Get
                Return ResourceManager.GetString("AdvancedWorking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Yearly.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedYearly() As String
            Get
                Return ResourceManager.GetString("AdvancedYearly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a year(s).
        '''</summary>
        Friend Shared ReadOnly Property AdvancedYears() As String
            Get
                Return ResourceManager.GetString("AdvancedYears", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a all day.
        '''</summary>
        Friend Shared ReadOnly Property AllDay() As String
            Get
                Return ResourceManager.GetString("AllDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmCancel() As String
            Get
                Return ResourceManager.GetString("ConfirmCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to delete this appointment?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmDeleteText() As String
            Get
                Return ResourceManager.GetString("ConfirmDeleteText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirm delete.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmDeleteTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a OK.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmOK() As String
            Get
                Return ResourceManager.GetString("ConfirmOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete only this occurrence..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceDeleteOccurrence() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceDeleteOccurrence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete the series..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceDeleteSeries() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceDeleteSeries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Deleting a recurring appointment.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceDeleteTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceDeleteTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Edit only this occurrence..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceEditOccurrence() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceEditOccurrence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Edit the series..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceEditSeries() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceEditSeries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Editing a recurring appointment.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceEditTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceEditTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Move only this occurrence..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceMoveOccurrence() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceMoveOccurrence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Move the series..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceMoveSeries() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceMoveSeries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Moving a recurring appointment.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceMoveTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceMoveTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Resize only this occurrence..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceResizeOccurrence() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceResizeOccurrence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Resize the series..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceResizeSeries() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceResizeSeries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Resizing a recurring appointment.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceResizeTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceResizeTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Do you want to delete all existing recurrence exceptions?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmResetExceptionsText() As String
            Get
                Return ResourceManager.GetString("ConfirmResetExceptionsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirm reset exceptions.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmResetExceptionsTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmResetExceptionsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New Appointment.
        '''</summary>
        Friend Shared ReadOnly Property ContextMenuAddAppointment() As String
            Get
                Return ResourceManager.GetString("ContextMenuAddAppointment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New Recurring Appointment.
        '''</summary>
        Friend Shared ReadOnly Property ContextMenuAddRecurringAppointment() As String
            Get
                Return ResourceManager.GetString("ContextMenuAddRecurringAppointment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete.
        '''</summary>
        Friend Shared ReadOnly Property ContextMenuDelete() As String
            Get
                Return ResourceManager.GetString("ContextMenuDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Edit.
        '''</summary>
        Friend Shared ReadOnly Property ContextMenuEdit() As String
            Get
                Return ResourceManager.GetString("ContextMenuEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Go to today.
        '''</summary>
        Friend Shared ReadOnly Property ContextMenuGoToToday() As String
            Get
                Return ResourceManager.GetString("ContextMenuGoToToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Day.
        '''</summary>
        Friend Shared ReadOnly Property HeaderDay() As String
            Get
                Return ResourceManager.GetString("HeaderDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Month.
        '''</summary>
        Friend Shared ReadOnly Property HeaderMonth() As String
            Get
                Return ResourceManager.GetString("HeaderMonth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Multi-day.
        '''</summary>
        Friend Shared ReadOnly Property HeaderMultiDay() As String
            Get
                Return ResourceManager.GetString("HeaderMultiDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a next day.
        '''</summary>
        Friend Shared ReadOnly Property HeaderNextDay() As String
            Get
                Return ResourceManager.GetString("HeaderNextDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a previous day.
        '''</summary>
        Friend Shared ReadOnly Property HeaderPrevDay() As String
            Get
                Return ResourceManager.GetString("HeaderPrevDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Timeline.
        '''</summary>
        Friend Shared ReadOnly Property HeaderTimeline() As String
            Get
                Return ResourceManager.GetString("HeaderTimeline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a today.
        '''</summary>
        Friend Shared ReadOnly Property HeaderToday() As String
            Get
                Return ResourceManager.GetString("HeaderToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Week.
        '''</summary>
        Friend Shared ReadOnly Property HeaderWeek() As String
            Get
                Return ResourceManager.GetString("HeaderWeek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reminder.
        '''</summary>
        Friend Shared ReadOnly Property Reminder() As String
            Get
                Return ResourceManager.GetString("Reminder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a before start.
        '''</summary>
        Friend Shared ReadOnly Property ReminderBeforeStart() As String
            Get
                Return ResourceManager.GetString("ReminderBeforeStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a day.
        '''</summary>
        Friend Shared ReadOnly Property ReminderDay() As String
            Get
                Return ResourceManager.GetString("ReminderDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a days.
        '''</summary>
        Friend Shared ReadOnly Property ReminderDays() As String
            Get
                Return ResourceManager.GetString("ReminderDays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dismiss.
        '''</summary>
        Friend Shared ReadOnly Property ReminderDismiss() As String
            Get
                Return ResourceManager.GetString("ReminderDismiss", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dismiss All.
        '''</summary>
        Friend Shared ReadOnly Property ReminderDismissAll() As String
            Get
                Return ResourceManager.GetString("ReminderDismissAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a due in.
        '''</summary>
        Friend Shared ReadOnly Property ReminderDueIn() As String
            Get
                Return ResourceManager.GetString("ReminderDueIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a hour.
        '''</summary>
        Friend Shared ReadOnly Property ReminderHour() As String
            Get
                Return ResourceManager.GetString("ReminderHour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a hours.
        '''</summary>
        Friend Shared ReadOnly Property ReminderHours() As String
            Get
                Return ResourceManager.GetString("ReminderHours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a minute.
        '''</summary>
        Friend Shared ReadOnly Property ReminderMinute() As String
            Get
                Return ResourceManager.GetString("ReminderMinute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a minutes.
        '''</summary>
        Friend Shared ReadOnly Property ReminderMinutes() As String
            Get
                Return ResourceManager.GetString("ReminderMinutes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a None.
        '''</summary>
        Friend Shared ReadOnly Property ReminderNone() As String
            Get
                Return ResourceManager.GetString("ReminderNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Open Item.
        '''</summary>
        Friend Shared ReadOnly Property ReminderOpenItem() As String
            Get
                Return ResourceManager.GetString("ReminderOpenItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a overdue.
        '''</summary>
        Friend Shared ReadOnly Property ReminderOverdue() As String
            Get
                Return ResourceManager.GetString("ReminderOverdue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reminders.
        '''</summary>
        Friend Shared ReadOnly Property Reminders() As String
            Get
                Return ResourceManager.GetString("Reminders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Snooze.
        '''</summary>
        Friend Shared ReadOnly Property ReminderSnooze() As String
            Get
                Return ResourceManager.GetString("ReminderSnooze", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Click Snooze to be reminded again in:.
        '''</summary>
        Friend Shared ReadOnly Property ReminderSnoozeHint() As String
            Get
                Return ResourceManager.GetString("ReminderSnoozeHint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a week.
        '''</summary>
        Friend Shared ReadOnly Property ReminderWeek() As String
            Get
                Return ResourceManager.GetString("ReminderWeek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a weeks.
        '''</summary>
        Friend Shared ReadOnly Property ReminderWeeks() As String
            Get
                Return ResourceManager.GetString("ReminderWeeks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please do not remove this key..
        '''</summary>
        Friend Shared ReadOnly Property ReservedResource() As String
            Get
                Return ResourceManager.GetString("ReservedResource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Save.
        '''</summary>
        Friend Shared ReadOnly Property Save() As String
            Get
                Return ResourceManager.GetString("Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Show 24 hours....
        '''</summary>
        Friend Shared ReadOnly Property Show24Hours() As String
            Get
                Return ResourceManager.GetString("Show24Hours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Options.
        '''</summary>
        Friend Shared ReadOnly Property ShowAdvancedForm() As String
            Get
                Return ResourceManager.GetString("ShowAdvancedForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Show business hours....
        '''</summary>
        Friend Shared ReadOnly Property ShowBusinessHours() As String
            Get
                Return ResourceManager.GetString("ShowBusinessHours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a more....
        '''</summary>
        Friend Shared ReadOnly Property ShowMore() As String
            Get
                Return ResourceManager.GetString("ShowMore", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
