'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace EnjoyPuntosTest
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://services.enjoy.cl/", ConfigurationName:="EnjoyPuntosTest.wsAlianzaLanDMZSoap")>  _
    Public Interface wsAlianzaLanDMZSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://services.enjoy.cl/validaCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function validaCliente(ByVal apellido As String, ByVal nombre As String, ByVal sexo As Integer, ByVal fecha_nacimiento As String, ByVal rut As String, ByVal telefono As String, ByVal email As String, ByVal movil As String, ByVal pais As String, ByVal token As String) As EnjoyPuntosTest.RespuestaAlianza
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://services.enjoy.cl/validaCliente", ReplyAction:="*")>  _
        Function validaClienteAsync(ByVal apellido As String, ByVal nombre As String, ByVal sexo As Integer, ByVal fecha_nacimiento As String, ByVal rut As String, ByVal telefono As String, ByVal email As String, ByVal movil As String, ByVal pais As String, ByVal token As String) As System.Threading.Tasks.Task(Of EnjoyPuntosTest.RespuestaAlianza)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://services.enjoy.cl/registrarPuntos", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function registrarPuntos(ByVal rut As String, ByVal puntos As Integer, ByVal cod_transaccion As String, ByVal token As String) As EnjoyPuntosTest.RespuestaAlianza
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://services.enjoy.cl/registrarPuntos", ReplyAction:="*")>  _
        Function registrarPuntosAsync(ByVal rut As String, ByVal puntos As Integer, ByVal cod_transaccion As String, ByVal token As String) As System.Threading.Tasks.Task(Of EnjoyPuntosTest.RespuestaAlianza)
    End Interface
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://services.enjoy.cl/")>  _
    Partial Public Class RespuestaAlianza
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private cod_ErrorField As String
        
        Private mensajeField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Cod_Error() As String
            Get
                Return Me.cod_ErrorField
            End Get
            Set
                Me.cod_ErrorField = value
                Me.RaisePropertyChanged("Cod_Error")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("Mensaje")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsAlianzaLanDMZSoapChannel
        Inherits EnjoyPuntosTest.wsAlianzaLanDMZSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsAlianzaLanDMZSoapClient
        Inherits System.ServiceModel.ClientBase(Of EnjoyPuntosTest.wsAlianzaLanDMZSoap)
        Implements EnjoyPuntosTest.wsAlianzaLanDMZSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function validaCliente(ByVal apellido As String, ByVal nombre As String, ByVal sexo As Integer, ByVal fecha_nacimiento As String, ByVal rut As String, ByVal telefono As String, ByVal email As String, ByVal movil As String, ByVal pais As String, ByVal token As String) As EnjoyPuntosTest.RespuestaAlianza Implements EnjoyPuntosTest.wsAlianzaLanDMZSoap.validaCliente
            Return MyBase.Channel.validaCliente(apellido, nombre, sexo, fecha_nacimiento, rut, telefono, email, movil, pais, token)
        End Function
        
        Public Function validaClienteAsync(ByVal apellido As String, ByVal nombre As String, ByVal sexo As Integer, ByVal fecha_nacimiento As String, ByVal rut As String, ByVal telefono As String, ByVal email As String, ByVal movil As String, ByVal pais As String, ByVal token As String) As System.Threading.Tasks.Task(Of EnjoyPuntosTest.RespuestaAlianza) Implements EnjoyPuntosTest.wsAlianzaLanDMZSoap.validaClienteAsync
            Return MyBase.Channel.validaClienteAsync(apellido, nombre, sexo, fecha_nacimiento, rut, telefono, email, movil, pais, token)
        End Function
        
        Public Function registrarPuntos(ByVal rut As String, ByVal puntos As Integer, ByVal cod_transaccion As String, ByVal token As String) As EnjoyPuntosTest.RespuestaAlianza Implements EnjoyPuntosTest.wsAlianzaLanDMZSoap.registrarPuntos
            Return MyBase.Channel.registrarPuntos(rut, puntos, cod_transaccion, token)
        End Function
        
        Public Function registrarPuntosAsync(ByVal rut As String, ByVal puntos As Integer, ByVal cod_transaccion As String, ByVal token As String) As System.Threading.Tasks.Task(Of EnjoyPuntosTest.RespuestaAlianza) Implements EnjoyPuntosTest.wsAlianzaLanDMZSoap.registrarPuntosAsync
            Return MyBase.Channel.registrarPuntosAsync(rut, puntos, cod_transaccion, token)
        End Function
    End Class
End Namespace
